# Generated by Django 4.2.7 on 2024-01-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_entry_incomecategory_delete_expense_delete_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('business_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('rent_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('remittances', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('other', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
    ]
