# Generated by Django 4.2.7 on 2024-01-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_financialentry_delete_entry_delete_incomecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utilities', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('groceries_shopping', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('transportation', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('cafe_restaurant', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('health', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('other', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
